In [ ]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
import statistics

In [ ]:
from sklearn import preprocessing

In [ ]:
X = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X.csv')
y = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y.csv')

In [ ]:
columns_to_drop = ['Unnamed: 0']
X.drop(columns=columns_to_drop, inplace=True)
y.drop(columns=columns_to_drop, inplace=True)

In [ ]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score,classification_report,confusion_matrix

In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_reshaped = np.reshape(X_train_scaled, (X_train_scaled.shape[0], X_train_scaled.shape[1], 1))
X_test_reshaped = np.reshape(X_test_scaled, (X_test_scaled.shape[0], X_test_scaled.shape[1], 1))
print('X_train_reshaped:',X_train_reshaped.shape)
print('X_test_reshaped:',X_test_reshaped.shape)

X_train_reshaped: (138505, 25, 1)
X_test_reshaped: (34627, 25, 1)


In [ ]:
from tensorflow.keras.layers import Bidirectional

model = Sequential()
model.add(Bidirectional(LSTM(units=128, return_sequences=True), input_shape=(X_train_reshaped.shape[1], 1)))
model.add(Bidirectional(LSTM(units=64, return_sequences=True)))
model.add(Bidirectional(LSTM(units=32, return_sequences=False)))
model.add(Dense(units=1, activation='sigmoid'))

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Print the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirection  (None, 25, 256)           133120    
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (None, 25, 128)           164352    
 onal)                                                           
                                                                 
 bidirectional_2 (Bidirecti  (None, 64)                41216     
 onal)                                                           
                                                                 
 dense (Dense)               (None, 1)                 65        
                                                                 
Total params: 338753 (1.29 MB)
Trainable params: 338753 (1.29 MB)
Non-trainable params: 0 (0.00 Byte)
____________________

In [ ]:
# Train the model
model.fit(X_train_reshaped, y_train, epochs=2, batch_size=64, validation_data=(X_test_reshaped, y_test))

Epoch 1/2
2165/2165 [==============================] - 58s 20ms/step - loss: 0.0678 - accuracy: 0.9738 - val_loss: 0.0158 - val_accuracy: 0.9958
Epoch 2/2
2165/2165 [==============================] - 37s 17ms/step - loss: 0.0197 - accuracy: 0.9947 - val_loss: 0.0081 - val_accuracy: 0.9984


In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_test_reshaped, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

1083/1083 [==============================] - 7s 6ms/step - loss: 0.0081 - accuracy: 0.9984
Test Loss: 0.008064396679401398
Test Accuracy: 0.9984116554260254


In [ ]:
# Run predictions on the test set
y_pred = model.predict(X_test_reshaped)

# If your model is for binary classification with a sigmoid activation
# You can threshold the predictions to get binary results
binary_predictions = (y_pred > 0.5).astype(int)

1083/1083 [==============================] - 9s 6ms/step


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Example evaluation
accuracy = accuracy_score(y_test, binary_predictions)
precision = precision_score(y_test, binary_predictions)
recall = recall_score(y_test, binary_predictions)
f1 = f1_score(y_test, binary_predictions)

conf_matrix = confusion_matrix(y_test, binary_predictions)

print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Precision: {precision * 100:.2f}%')
print(f'Recall: {recall * 100:.2f}%')
print(f'F1 Score: {f1 * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 99.84%
Precision: 99.77%
Recall: 99.99%
F1 Score: 99.88%
Confusion Matrix:
[[11791    53]
 [    2 22781]]


In [ ]:
model.save('DDOS_LSTM_partsDataset_v2.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
X_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS20.csv')
y_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS20.csv')

In [ ]:
columns_to_drop = ['Unnamed: 0']
X_20.drop(columns=columns_to_drop, inplace=True)
y_20.drop(columns=columns_to_drop, inplace=True)

In [ ]:
scaler = MinMaxScaler()
X_20_scaled = scaler.fit_transform(X_20)

In [ ]:
X_20_reshaped = np.reshape(X_20_scaled, (X_20_scaled.shape[0], X_20_scaled.shape[1], 1))

In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_20_reshaped, y_20)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

351/351 [==============================] - 3s 9ms/step - loss: 0.1968 - accuracy: 0.8629
Test Loss: 0.19678165018558502
Test Accuracy: 0.8628903031349182


In [ ]:
# Run predictions on the test set
y20_pred = model.predict(X_20_reshaped)

# If your model is for binary classification with a sigmoid activation
# You can threshold the predictions to get binary results
binary_predictions_20 = (y20_pred > 0.5).astype(int)

351/351 [==============================] - 2s 6ms/step


In [ ]:
from imblearn.metrics import specificity_score

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score, precision_score, classification_report,confusion_matrix, recall_score, f1_score

In [ ]:
accuracy = accuracy_score(y_20, binary_predictions_20)
precision = precision_score(y_20, binary_predictions_20)
recall = recall_score(y_20, binary_predictions_20)
f1 = f1_score(y_20, binary_predictions_20)
specificity = specificity_score(y_20, binary_predictions_20)

conf_matrix = confusion_matrix(y_20, binary_predictions_20)

print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Precision: {precision * 100:.2f}%')
print(f'Recall: {recall * 100:.2f}%')
print(f'F1 Score: {f1 * 100:.2f}%')
print(f'specificity Score: {specificity * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 86.29%
Precision: 98.75%
Recall: 77.09%
F1 Score: 86.59%
specificity Score: 98.68%
Confusion Matrix:
[[4712   63]
 [1474 4961]]


In [ ]:
from time import time

In [ ]:
for i in range(len(X_20_reshaped)):
  features_20 = X_20_reshaped[[i]]
  label_20 = y_20.iloc[i].to_numpy()
  if(label_20 == [1]):
    start_20 = time()
  prediction_20 = model.predict(features_20)
  binary_prediction_20 = (prediction_20 > 0.5).astype(int)
  if(binary_prediction_20 == [[1]]):
    end_20 = time()
  print(label_20)
  print(binary_prediction_20)

Выходные данные были обрезаны до нескольких последних строк (5000).
[1]
[[0]]
1/1 [==============================] - 0s 23ms/step
[1]
[[1]]
1/1 [==============================] - 0s 21ms/step
[1]
[[0]]
1/1 [==============================] - 0s 33ms/step
[1]
[[1]]
1/1 [==============================] - 0s 22ms/step
[1]
[[0]]
1/1 [==============================] - 0s 24ms/step
[1]
[[1]]
1/1 [==============================] - 0s 24ms/step
[1]
[[0]]
1/1 [==============================] - 0s 21ms/step
[1]
[[1]]
1/1 [==============================] - 0s 20ms/step
[1]
[[0]]
1/1 [==============================] - 0s 21ms/step
[1]
[[1]]
1/1 [==============================] - 0s 21ms/step
[1]
[[0]]
1/1 [==============================] - 0s 22ms/step
[1]
[[1]]
1/1 [==============================] - 0s 21ms/step
[1]
[[0]]
1/1 [==============================] - 0s 21ms/step
[1]
[[1]]
1/1 [==============================] - 0s 25ms/step
[1]
[[0]]
1/1 [==============================] - 0s 24ms/step
[1

In [ ]:
time_20 = end_20 - start_20
print(time_20)

0.11459732055664062


In [ ]:
X_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS21.csv')
y_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS21.csv')

In [ ]:
columns_to_drop = ['Unnamed: 0']
X_21.drop(columns=columns_to_drop, inplace=True)
y_21.drop(columns=columns_to_drop, inplace=True)

In [ ]:
X_21_scaled = scaler.fit_transform(X_21)

In [ ]:
X_21_reshaped = np.reshape(X_21_scaled, (X_21_scaled.shape[0], X_21_scaled.shape[1], 1))

In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_21_reshaped, y_21)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

285/285 [==============================] - 2s 7ms/step - loss: 0.4502 - accuracy: 0.6137
Test Loss: 0.45016708970069885
Test Accuracy: 0.6136862635612488


In [ ]:
# Run predictions on the test set
y21_pred = model.predict(X_21_reshaped)

# If your model is for binary classification with a sigmoid activation
# You can threshold the predictions to get binary results
binary_predictions_21 = (y21_pred > 0.5).astype(int)

285/285 [==============================] - 2s 6ms/step


In [ ]:
accuracy = accuracy_score(y_21, binary_predictions_21)
precision = precision_score(y_21, binary_predictions_21)
recall = recall_score(y_21, binary_predictions_21)
f1 = f1_score(y_21, binary_predictions_21)
specificity = specificity_score(y_21, binary_predictions_21)

conf_matrix = confusion_matrix(y_21, binary_predictions_21)

print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Precision: {precision * 100:.2f}%')
print(f'Recall: {recall * 100:.2f}%')
print(f'F1 Score: {f1 * 100:.2f}%')
print(f'specificity Score: {specificity * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 61.37%
Precision: 100.00%
Recall: 43.86%
F1 Score: 60.98%
specificity Score: 100.00%
Confusion Matrix:
[[2839    0]
 [3517 2748]]


In [ ]:
from time import time

In [ ]:
for i in range(len(X_21_reshaped)):
  features_21 = X_21_reshaped[[i]]
  label_21 = y_21.iloc[i].to_numpy()
  if(label_21 == [1]):
    start_21 = time()
  prediction_21 = model.predict(features_21)
  binary_prediction_21 = (prediction_21 > 0.5).astype(int)
  if(binary_prediction_21 == [[1]]):
    end_21 = time()
  print(label_21)
  print(binary_prediction_21)

Выходные данные были обрезаны до нескольких последних строк (5000).
[1]
[[0]]
1/1 [==============================] - 0s 39ms/step
[1]
[[1]]
1/1 [==============================] - 0s 40ms/step
[1]
[[0]]
1/1 [==============================] - 0s 37ms/step
[1]
[[1]]
1/1 [==============================] - 0s 46ms/step
[1]
[[0]]
1/1 [==============================] - 0s 28ms/step
[1]
[[1]]
1/1 [==============================] - 0s 21ms/step
[1]
[[0]]
1/1 [==============================] - 0s 25ms/step
[1]
[[1]]
1/1 [==============================] - 0s 23ms/step
[1]
[[0]]
1/1 [==============================] - 0s 24ms/step
[1]
[[1]]
1/1 [==============================] - 0s 23ms/step
[1]
[[0]]
1/1 [==============================] - 0s 22ms/step
[1]
[[1]]
1/1 [==============================] - 0s 21ms/step
[1]
[[0]]
1/1 [==============================] - 0s 24ms/step
[1]
[[1]]
1/1 [==============================] - 0s 26ms/step
[1]
[[0]]
1/1 [==============================] - 0s 24ms/step
[1

In [ ]:
time_21 = end_21 - start_21
print(time_21)

0.09821248054504395


In [ ]:
X_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS22.csv')
y_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS22.csv')

In [ ]:
columns_to_drop = ['Unnamed: 0']
X_22.drop(columns=columns_to_drop, inplace=True)
y_22.drop(columns=columns_to_drop, inplace=True)

In [ ]:
X_22_scaled = scaler.fit_transform(X_22)

In [ ]:
X_22_reshaped = np.reshape(X_22_scaled, (X_22_scaled.shape[0], X_22_scaled.shape[1], 1))

In [ ]:
# Evaluate the model
loss, accuracy = model.evaluate(X_22_reshaped, y_22)
print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

129/129 [==============================] - 1s 7ms/step - loss: 0.2055 - accuracy: 0.8191
Test Loss: 0.20553354918956757
Test Accuracy: 0.8191359639167786


In [ ]:
# Run predictions on the test set
y22_pred = model.predict(X_22_reshaped)

# If your model is for binary classification with a sigmoid activation
# You can threshold the predictions to get binary results
binary_predictions_22 = (y22_pred > 0.5).astype(int)

129/129 [==============================] - 1s 6ms/step


In [ ]:
accuracy = accuracy_score(y_22, binary_predictions_22)
precision = precision_score(y_22, binary_predictions_22)
recall = recall_score(y_22, binary_predictions_22)
f1 = f1_score(y_22, binary_predictions_22)
specificity = specificity_score(y_22, binary_predictions_22)

conf_matrix = confusion_matrix(y_22, binary_predictions_22)

print(f'Accuracy: {accuracy * 100:.2f}%')
print(f'Precision: {precision * 100:.2f}%')
print(f'Recall: {recall * 100:.2f}%')
print(f'F1 Score: {f1 * 100:.2f}%')
print(f'specificity Score: {specificity * 100:.2f}%')
print('Confusion Matrix:')
print(conf_matrix)

Accuracy: 81.91%
Precision: 90.31%
Recall: 50.45%
F1 Score: 64.73%
specificity Score: 97.34%
Confusion Matrix:
[[2676   73]
 [ 668  680]]


In [ ]:
from time import time

In [ ]:
for i in range(len(X_22_reshaped)):
  features_22 = X_22_reshaped[[i]]
  label_22 = y_22.iloc[i].to_numpy()
  if(label_22 == [1]):
    start_22 = time()
  prediction_22 = model.predict(features_22)
  binary_prediction_22 = (prediction_22 > 0.5).astype(int)
  if(binary_prediction_22 == [[1]]):
    end_22 = time()
  print(label_22)
  print(binary_prediction_22)

Выходные данные были обрезаны до нескольких последних строк (5000).
[0]
[[0]]
1/1 [==============================] - 0s 26ms/step
[0]
[[0]]
1/1 [==============================] - 0s 25ms/step
[0]
[[0]]
1/1 [==============================] - 0s 25ms/step
[0]
[[0]]
1/1 [==============================] - 0s 27ms/step
[0]
[[0]]
1/1 [==============================] - 0s 27ms/step
[0]
[[0]]
1/1 [==============================] - 0s 27ms/step
[0]
[[0]]
1/1 [==============================] - 0s 26ms/step
[0]
[[0]]
1/1 [==============================] - 0s 26ms/step
[0]
[[0]]
1/1 [==============================] - 0s 28ms/step
[0]
[[1]]
1/1 [==============================] - 0s 26ms/step
[0]
[[0]]
1/1 [==============================] - 0s 31ms/step
[0]
[[0]]
1/1 [==============================] - 0s 26ms/step
[0]
[[1]]
1/1 [==============================] - 0s 25ms/step
[0]
[[0]]
1/1 [==============================] - 0s 25ms/step
[0]
[[0]]
1/1 [==============================] - 0s 27ms/step
[0

In [ ]:
time_22 = end_22 - start_22
print(time_22)

-0.0007650852203369141


26 мили секунд