In [1]:
import os
import joblib

In [2]:
from time import time

In [3]:
import numpy as np
import pandas as pd

In [4]:
import os
import joblib

In [5]:
model_rf = joblib.load("/content/drive/MyDrive/diplom/models/itog/RandomForestClassifier_V3.joblib")

In [12]:
X_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS20.csv')
y_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS20.csv')

X_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS21.csv')
y_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS21.csv')

X_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS22.csv')
y_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS22.csv')

In [13]:
columns_to_drop = ['Unnamed: 0']
X_20.drop(columns=columns_to_drop, inplace=True)
y_20.drop(columns=columns_to_drop, inplace=True)

X_21.drop(columns=columns_to_drop, inplace=True)
y_21.drop(columns=columns_to_drop, inplace=True)

X_22.drop(columns=columns_to_drop, inplace=True)
y_22.drop(columns=columns_to_drop, inplace=True)

In [14]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score, precision_score, classification_report,confusion_matrix, recall_score, f1_score



---



In [15]:
binary_predictions_20 = model_rf.predict(X_20)

In [17]:
accuracy_20 = accuracy_score(y_20, binary_predictions_20)
precision_20 = precision_score(y_20, binary_predictions_20)
recall_20 = recall_score(y_20, binary_predictions_20)
f1_20 = f1_score(y_20, binary_predictions_20)

conf_matrix_20 = confusion_matrix(y_20, binary_predictions_20)

tn_20, fp_20, fn_20, tp_20 = confusion_matrix(y_20, binary_predictions_20).ravel()
specificity_20 = tn_20 / (tn_20+fp_20)

print(f'Accuracy: {accuracy_20 * 100:.2f}%')
print(f'Precision: {precision_20 * 100:.2f}%')
print(f'Recall: {recall_20 * 100:.2f}%')
print(f'Specificity: {specificity_20 * 100:.2f}%')
print(f'F1 Score: {f1_20 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_20)

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
Specificity: 100.00%
F1 Score: 100.00%
Confusion Matrix:
[[4775    0]
 [   0 6435]]


In [18]:
from time import time

In [19]:
for i in range(len(X_20)):
  features = X_20.iloc[i].to_frame().T
  label = y_20.iloc[i].to_numpy()
  if(label == [1]):
    start_20 = time()
  prediction = model_rf.predict(features)
  if(prediction == [1]):
    end_20 = time()
    break

In [20]:
time_20 = end_20 - start_20
print(time_20)

0.0022869110107421875




---



In [21]:
binary_predictions_21 = model_rf.predict(X_21)

In [22]:
accuracy_21 = accuracy_score(y_21, binary_predictions_21)
precision_21 = precision_score(y_21, binary_predictions_21)
recall_21 = recall_score(y_21, binary_predictions_21)
f1_21 = f1_score(y_21, binary_predictions_21)

conf_matrix_21 = confusion_matrix(y_21, binary_predictions_21)

tn_21, fp_21, fn_21, tp_21 = confusion_matrix(y_21, binary_predictions_21).ravel()
specificity_21 = tn_21 / (tn_21+fp_21)

print(f'Accuracy: {accuracy_21 * 100:.2f}%')
print(f'Precision: {precision_21 * 100:.2f}%')
print(f'Recall: {recall_21 * 100:.2f}%')
print(f'Specificity: {specificity_21 * 100:.2f}%')
print(f'F1 Score: {f1_21 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_21)

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
Specificity: 100.00%
F1 Score: 100.00%
Confusion Matrix:
[[2839    0]
 [   0 6265]]


In [23]:
from time import time

In [24]:
for i in range(len(X_21)):
  features = X_21.iloc[i].to_frame().T
  label = y_21.iloc[i].to_numpy()
  if(label == [1]):
    start_21 = time()
  prediction = model_rf.predict(features)
  if(prediction == [1]):
    end_21 = time()
    break

In [25]:
time_21 = end_21 - start_21
print(time_21)

0.0025284290313720703




---



In [26]:
binary_predictions_22 = model_rf.predict(X_22)

In [27]:
accuracy_22 = accuracy_score(y_22, binary_predictions_22)
precision_22 = precision_score(y_22, binary_predictions_22)
recall_22 = recall_score(y_22, binary_predictions_22)
f1_22 = f1_score(y_22, binary_predictions_22)

conf_matrix_22 = confusion_matrix(y_22, binary_predictions_22)

tn_22, fp_22, fn_22, tp_22 = confusion_matrix(y_22, binary_predictions_22).ravel()
specificity_22 = tn_22 / (tn_22+fp_22)

print(f'Accuracy: {accuracy_22 * 100:.2f}%')
print(f'Precision: {precision_22 * 100:.2f}%')
print(f'Recall: {recall_22 * 100:.2f}%')
print(f'Specificity: {specificity_22 * 100:.2f}%')
print(f'F1 Score: {f1_22 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_22)

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
Specificity: 100.00%
F1 Score: 100.00%
Confusion Matrix:
[[2749    0]
 [   0 1348]]


In [28]:
from time import time

In [29]:
for i in range(len(X_22)):
  features = X_22.iloc[i].to_frame().T
  label = y_22.iloc[i].to_numpy()
  if(label == [1]):
    start_22 = time()
  prediction = model_rf.predict(features)
  if(prediction == [1]):
    end_22 = time()
    break

In [30]:
time_22 = end_22 - start_22
print(time_22)

0.0022330284118652344
