In [1]:
import os
import joblib

In [2]:
import numpy as np
import pandas as pd

In [4]:
X = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X.csv')
y = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y.csv')

In [5]:
columns_to_drop = ['Unnamed: 0']
X.drop(columns=columns_to_drop, inplace=True)
y.drop(columns=columns_to_drop, inplace=True)

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 173132 entries, 0 to 173131
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   Flow ID                  173132 non-null  int64  
 1    Source IP               173132 non-null  int64  
 2    Source Port             173132 non-null  int64  
 3    Destination IP          173132 non-null  int64  
 4    Destination Port        173132 non-null  int64  
 5    Protocol                173132 non-null  int64  
 6    Timestamp               173132 non-null  int64  
 7    Fwd Packet Length Max   173132 non-null  int64  
 8    Fwd Packet Length Mean  173132 non-null  float64
 9   Bwd Packet Length Max    173132 non-null  int64  
 10   Bwd Packet Length Min   173132 non-null  int64  
 11   Bwd Packet Length Mean  173132 non-null  float64
 12   Bwd Packet Length Std   173132 non-null  float64
 13   Min Packet Length       173132 non-null  int64  
 14   Max

In [7]:
X

Flow ID   Source IP   Source Port   Destination IP   Destination Port  \
0         82985          22           443              866              54865   
1         83017          37            80              866              55054   
2         83018          37            80              866              55055   
3         57106          45           443              860              46236   
4         83023          49           443              866              54863   
...         ...         ...           ...              ...                ...   
173127    26841         426         39661              867                 80   
173128    26842         426         39662              867                 80   
173129    26843         426         39663              867                 80   
173130    26844         426         39664              867                 80   
173131    26845         426         39665              867                 80   

         Protocol   Timestamp   Fwd Packet Length Max  \
0               6           0                       6   
1               6           0                       6   
2               6           0                       6   
3               6           0                       6   
4               6           0                       6   
...           ...         ...                     ...   
173127          6          43                      20   
173128          6          43                      20   
173129          6          43                      20   
173130          6          43                      20   
173131          6          43                      20   

         Fwd Packet Length Mean  Bwd Packet Length Max  ...  \
0                      6.000000                      0  ...   
1                      6.000000                      6  ...   
2                      6.000000                      6  ...   
3                      6.000000                      6  ...   
4                      6.000000                      0  ...   
...                         ...                    ...  ...   
173127                 8.666667                   7215  ...   
173128                 8.666667                   7215  ...   
173129                 8.666667                   5840  ...   
173130                 8.666667                  11595  ...   
173131                 8.666667                   7215  ...   

         Packet Length Mean   Packet Length Std   Packet Length Variance  \
0                  6.000000            0.000000             0.000000e+00   
1                  6.000000            0.000000             0.000000e+00   
2                  6.000000            0.000000             0.000000e+00   
3                  6.000000            0.000000             0.000000e+00   
4                  6.000000            0.000000             0.000000e+00   
...                     ...                 ...                      ...   
173127          1292.555556         2650.585648             7.025604e+06   
173128          1292.555556         2650.585648             7.025604e+06   
173129          1292.555556         2554.159212             6.523729e+06   
173130          1454.125000         4097.537534             1.680000e+07   
173131          1292.555556         2650.585648             7.025604e+06   

         PSH Flag Count   ACK Flag Count   URG Flag Count   Down/Up Ratio  \
0                     0                1                0               0   
1                     0                1                1               1   
2                     0                1                1               1   
3                     0                1                1               1   
4                     0                1                0               0   
...                 ...              ...              ...             ...   
173127                1                0                0               1   
173128                1                0                0       

In [8]:
y

Label
0           0
1           0
2           0
3           0
4           0
...       ...
173127      1
173128      1
173129      1
173130      1
173131      1

[173132 rows x 1 columns]

In [9]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score,classification_report,confusion_matrix

In [10]:
import os
import joblib

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier()
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [13]:
acc_test = clf.score(X_test, y_test)
acc_test = acc_test * 100

print ("Test Accuracy: ", acc_test, "%")

Test Accuracy:  99.94801744303578 %


In [14]:
X_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS20.csv')
y_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS20.csv')

X_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS21.csv')
y_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS21.csv')

X_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS22.csv')
y_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS22.csv')

In [15]:
columns_to_drop = ['Unnamed: 0']
X_20.drop(columns=columns_to_drop, inplace=True)
y_20.drop(columns=columns_to_drop, inplace=True)

X_21.drop(columns=columns_to_drop, inplace=True)
y_21.drop(columns=columns_to_drop, inplace=True)

X_22.drop(columns=columns_to_drop, inplace=True)
y_22.drop(columns=columns_to_drop, inplace=True)

In [16]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score, precision_score, classification_report,confusion_matrix, recall_score, f1_score



---



In [17]:
binary_predictions_20 = clf.predict(X_20)

In [18]:
accuracy_20 = accuracy_score(y_20, binary_predictions_20)
precision_20 = precision_score(y_20, binary_predictions_20)
recall_20 = recall_score(y_20, binary_predictions_20)
f1_20 = f1_score(y_20, binary_predictions_20)

conf_matrix_20 = confusion_matrix(y_20, binary_predictions_20)

tn_20, fp_20, fn_20, tp_20 = confusion_matrix(y_20, binary_predictions_20).ravel()
specificity_20 = tn_20 / (tn_20+fp_20)

print(f'Accuracy: {accuracy_20 * 100:.2f}%')
print(f'Precision: {precision_20 * 100:.2f}%')
print(f'Recall: {recall_20 * 100:.2f}%')
print(f'Specificity: {specificity_20 * 100:.2f}%')
print(f'F1 Score: {f1_20 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_20)

Accuracy: 99.93%
Precision: 99.91%
Recall: 99.97%
Specificity: 99.87%
F1 Score: 99.94%
Confusion Matrix:
[[4769    6]
 [   2 6433]]


In [19]:
from time import time

In [26]:
for i in range(len(X_20)):
  features = X_20.iloc[i].to_frame().T
  label = y_20.iloc[i].to_numpy()
  if(label == [1]):
    start_20 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_20 = time()
    break

In [27]:
time_20 = end_20 - start_20
print(time_20)

0.012801408767700195




---



In [28]:
binary_predictions_21 = clf.predict(X_21)

In [29]:
accuracy_21 = accuracy_score(y_21, binary_predictions_21)
precision_21 = precision_score(y_21, binary_predictions_21)
recall_21 = recall_score(y_21, binary_predictions_21)
f1_21 = f1_score(y_21, binary_predictions_21)

conf_matrix_21 = confusion_matrix(y_21, binary_predictions_21)

tn_21, fp_21, fn_21, tp_21 = confusion_matrix(y_21, binary_predictions_21).ravel()
specificity_21 = tn_21 / (tn_21+fp_21)

print(f'Accuracy: {accuracy_21 * 100:.2f}%')
print(f'Precision: {precision_21 * 100:.2f}%')
print(f'Recall: {recall_21 * 100:.2f}%')
print(f'Specificity: {specificity_21 * 100:.2f}%')
print(f'F1 Score: {f1_21 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_21)

Accuracy: 99.97%
Precision: 99.97%
Recall: 99.98%
Specificity: 99.93%
F1 Score: 99.98%
Confusion Matrix:
[[2837    2]
 [   1 6264]]


In [30]:
from time import time

In [31]:
for i in range(len(X_21)):
  features = X_21.iloc[i].to_frame().T
  label = y_21.iloc[i].to_numpy()
  if(label == [1]):
    start_21 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_21 = time()
    break

In [32]:
time_21 = end_21 - start_21
print(time_21)

0.012080192565917969




---



In [33]:
binary_predictions_22 = clf.predict(X_22)

In [34]:
accuracy_22 = accuracy_score(y_22, binary_predictions_22)
precision_22 = precision_score(y_22, binary_predictions_22)
recall_22 = recall_score(y_22, binary_predictions_22)
f1_22 = f1_score(y_22, binary_predictions_22)

conf_matrix_22 = confusion_matrix(y_22, binary_predictions_22)

tn_22, fp_22, fn_22, tp_22 = confusion_matrix(y_22, binary_predictions_22).ravel()
specificity_22 = tn_22 / (tn_22+fp_22)

print(f'Accuracy: {accuracy_22 * 100:.2f}%')
print(f'Precision: {precision_22 * 100:.2f}%')
print(f'Recall: {recall_22 * 100:.2f}%')
print(f'Specificity: {specificity_22 * 100:.2f}%')
print(f'F1 Score: {f1_22 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_22)

Accuracy: 100.00%
Precision: 100.00%
Recall: 100.00%
Specificity: 100.00%
F1 Score: 100.00%
Confusion Matrix:
[[2749    0]
 [   0 1348]]


In [35]:
from time import time

In [36]:
for i in range(len(X_22)):
  features = X_22.iloc[i].to_frame().T
  label = y_22.iloc[i].to_numpy()
  if(label == [1]):
    start_22 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_22 = time()
    break

In [37]:
time_22 = end_22 - start_22
print(time_22)

0.009626388549804688
