In [1]:
import os
import joblib

In [2]:
import numpy as np
import pandas as pd

In [9]:
X = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X.csv')
y = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y.csv')

In [10]:
columns_to_drop = ['Unnamed: 0']
X.drop(columns=columns_to_drop, inplace=True)
y.drop(columns=columns_to_drop, inplace=True)

In [11]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score,classification_report,confusion_matrix

In [5]:
import os
import joblib

In [12]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
from sklearn.svm import SVC

# Create the SVM classifier
clf = SVC(kernel='rbf', C=1.0, gamma='scale')  # Using the RBF kernel

# Train the SVM classifier
clf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = clf.predict(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
acc_test = clf.score(X_test, y_test)
acc_test = acc_test * 100

print ("Test Accuracy: ", acc_test, "%")

Test Accuracy:  91.84451439628036 %


In [15]:
X_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS20.csv')
y_20 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS20.csv')

X_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS21.csv')
y_21 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS21.csv')

X_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/X_DDoS22.csv')
y_22 = pd.read_csv('/content/drive/MyDrive/diplom/dataset/PartsDataset/y_DDoS22.csv')

In [16]:
columns_to_drop = ['Unnamed: 0']
X_20.drop(columns=columns_to_drop, inplace=True)
y_20.drop(columns=columns_to_drop, inplace=True)

X_21.drop(columns=columns_to_drop, inplace=True)
y_21.drop(columns=columns_to_drop, inplace=True)

X_22.drop(columns=columns_to_drop, inplace=True)
y_22.drop(columns=columns_to_drop, inplace=True)

In [17]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, accuracy_score, precision_score, classification_report,confusion_matrix, recall_score, f1_score



---



In [18]:
binary_predictions_20 = clf.predict(X_20)

In [19]:
accuracy_20 = accuracy_score(y_20, binary_predictions_20)
precision_20 = precision_score(y_20, binary_predictions_20)
recall_20 = recall_score(y_20, binary_predictions_20)
f1_20 = f1_score(y_20, binary_predictions_20)

conf_matrix_20 = confusion_matrix(y_20, binary_predictions_20)

tn_20, fp_20, fn_20, tp_20 = confusion_matrix(y_20, binary_predictions_20).ravel()
specificity_20 = tn_20 / (tn_20+fp_20)

print(f'Accuracy: {accuracy_20 * 100:.2f}%')
print(f'Precision: {precision_20 * 100:.2f}%')
print(f'Recall: {recall_20 * 100:.2f}%')
print(f'Specificity: {specificity_20 * 100:.2f}%')
print(f'F1 Score: {f1_20 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_20)

Accuracy: 89.94%
Precision: 85.10%
Recall: 99.97%
Specificity: 76.42%
F1 Score: 91.94%
Confusion Matrix:
[[3649 1126]
 [   2 6433]]


In [20]:
from time import time

In [21]:
for i in range(len(X_20)):
  features = X_20.iloc[i].to_frame().T
  label = y_20.iloc[i].to_numpy()
  if(label == [1]):
    start_20 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_20 = time()
    break

In [22]:
time_20 = end_20 - start_20
print(time_20)

0.004812479019165039




---



In [23]:
binary_predictions_21 = clf.predict(X_21)

In [24]:
accuracy_21 = accuracy_score(y_21, binary_predictions_21)
precision_21 = precision_score(y_21, binary_predictions_21)
recall_21 = recall_score(y_21, binary_predictions_21)
f1_21 = f1_score(y_21, binary_predictions_21)

conf_matrix_21 = confusion_matrix(y_21, binary_predictions_21)

tn_21, fp_21, fn_21, tp_21 = confusion_matrix(y_21, binary_predictions_21).ravel()
specificity_21 = tn_21 / (tn_21+fp_21)

print(f'Accuracy: {accuracy_21 * 100:.2f}%')
print(f'Precision: {precision_21 * 100:.2f}%')
print(f'Recall: {recall_21 * 100:.2f}%')
print(f'Specificity: {specificity_21 * 100:.2f}%')
print(f'F1 Score: {f1_21 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_21)

Accuracy: 94.28%
Precision: 92.32%
Recall: 100.00%
Specificity: 81.65%
F1 Score: 96.01%
Confusion Matrix:
[[2318  521]
 [   0 6265]]


In [25]:
from time import time

In [26]:
for i in range(len(X_21)):
  features = X_21.iloc[i].to_frame().T
  label = y_21.iloc[i].to_numpy()
  if(label == [1]):
    start_21 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_21 = time()
    break

In [27]:
time_21 = end_21 - start_21
print(time_21)

0.004672050476074219




---



In [28]:
binary_predictions_22 = clf.predict(X_22)

In [29]:
accuracy_22 = accuracy_score(y_22, binary_predictions_22)
precision_22 = precision_score(y_22, binary_predictions_22)
recall_22 = recall_score(y_22, binary_predictions_22)
f1_22 = f1_score(y_22, binary_predictions_22)

conf_matrix_22 = confusion_matrix(y_22, binary_predictions_22)

tn_22, fp_22, fn_22, tp_22 = confusion_matrix(y_22, binary_predictions_22).ravel()
specificity_22 = tn_22 / (tn_22+fp_22)

print(f'Accuracy: {accuracy_22 * 100:.2f}%')
print(f'Precision: {precision_22 * 100:.2f}%')
print(f'Recall: {recall_22 * 100:.2f}%')
print(f'Specificity: {specificity_22 * 100:.2f}%')
print(f'F1 Score: {f1_22 * 100:.2f}%')

print('Confusion Matrix:')
print(conf_matrix_22)

Accuracy: 91.82%
Precision: 80.10%
Recall: 100.00%
Specificity: 87.81%
F1 Score: 88.95%
Confusion Matrix:
[[2414  335]
 [   0 1348]]


In [30]:
from time import time

In [31]:
for i in range(len(X_22)):
  features = X_22.iloc[i].to_frame().T
  label = y_22.iloc[i].to_numpy()
  if(label == [1]):
    start_22 = time()
  prediction = clf.predict(features)
  if(label == [1] and prediction == [1]):
    end_22 = time()
    break

In [32]:
time_22 = end_22 - start_22
print(time_22)

0.004860877990722656
